### PR TITLE
Update purple borders to something more subtle

### PR DESCRIPTION
**Pull request by deybhayden**
Hey there - this might just be a nitpick, but wanted to file it in case you were interested, on the `Solarized Dark+` theme I made the terminal border more subtle.

## Before

Screen Shot 2020-03-05 at 1 33 15 PM

## After

Screen Shot 2020-03-05 at 1 33 29 PM

Thanks for this great theme - I really enjoy it!

### CODE REVIEW

**Comment by ryanolsonx** [comment]
I totally dig it.  Thanks for the contribution! :D

**Comment by ryanolsonx** [comment]
I just pushed a new version to the marketplace (v2.0.3) that will include this change. 🎉

**Comment by ryanolsonx** [comment]
@deybhayden If you see any other issues, feel free to create issues or make future PRs.

**Comment by deybhayden** [comment]
Awesome, I appreciate @ryanolsonx! Thanks so much. 🙌🏻

**Pull request merged**
